unclassified:
  bundleStorageService:
    activated: true
    bundles:
    - name: "workshop-scm"
      retriever:
        SCM:
          scmSource:
            github:
              configuredByUrl: true
              credentialsId: "43640dc0-47df-4c21-af27-555604649f29"
              repositoryUrl: "https://github.com/poc-prep/cloud-config-bundle.git"
