apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Download Jenkins Cli
        uses: docker://openjdk
        shell: sh
        run: |
          curl -O https://sda.preview.cb-demos.io/cjoc/jnlpJars/jenkins-cli.jar
      - name: Setup shared agent
        uses: docker://openjdk
        shell: sh
        run: |
          java -jar ./jenkins-cli.jar -auth pyang:${{ secrets.THUNDER_OC_TOKEN }} -s https://sda.preview.cb-demos.io/cjoc/ shared-pod-template --get     
