apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    environment: workshop-pyang
    steps:
      - uses: docker://openjdk
        name: Download Jenkins Cli
        shell: sh
        run: |
          curl -O ${{ vars.oc-url }}/jnlpJars/jenkins-cli.jar
      - uses: cloudbees-io/checkout@v1
        name: Download Assets
        with:
          repository: cloudbees-pyang/CI-workshop-generator
          token: ${{ secrets.PYANG_GITHUB_TOKEN }}
          path: assets
#      - uses: docker://openjdk
#        name: Setup shared agent
#        shell: sh
#        run: |
#          java -jar ./jenkins-cli.jar -auth ${{ vars.USER_NAME }}:${{ secrets.OC_TOKEN }} -s ${{ vars.oc-url }} shared-pod-template --add <./assets/share-pod-template.json      
          
#      - uses: docker://poseidon1979/jenkins-cli:1.1
#        name: create credential
#        shell: sh
#        run: |
#          java -jar ./jenkins-cli.jar -auth ${{ vars.USER_NAME }}:${{ secrets.OC_TOKEN }} -s ${{ vars.oc-url }} create-credentials-by-xml system::system::jenkins "(global)" < ./assets/credential.xml

      - uses: docker://poseidon1979/jenkins-cli:1.1
        name: Add casc bundle
        shell: sh
        run: |
          java -jar ./jenkins-cli.jar -auth ${{ vars.USER_NAME }}:${{ secrets.OC_TOKEN }} -s ${{ vars.oc-url }} export-configuration >> ./oc-conf.yaml
          yq eval '.unclassified.bundleStorageService.bundles + [{ "myFile" : "./assets/oc-casc-config.yaml" }]' -i oc-conf.yaml 
          yq '(.. | select(has("myFile"))) |= load(.myFile)' -i oc-conf.yaml
          yq '.unclassified.bundleStorageService.bundles' oc-conf.yaml
#          yq eval '.unclassified.bundleStorageService.bundles += [{ "myFile" : "./assets/oc-casc-config.yaml" }]' -i oc-conf.yaml
#          yq '(.. | select(has("myFile"))) |= load(.myFile)' -i oc-conf.yaml 
#          java -jar ./jenkins-cli.jar -auth ${{ vars.USER_NAME }}:${{ secrets.OC_TOKEN }} -s ${{ vars.oc-url }} apply-configuration < oc-conf.yaml

#      - uses: docker://openjdk
#        name: Create Controller
#        shell: sh
#        run: |
#          java -jar ./jenkins-cli.jar -auth ${{ vars.USER_NAME }}:${{ secrets.OC_TOKEN }} -s ${{ vars.oc-url }} create-job workshop-controller <./assets/controller-config.xml     

#      - uses: docker://openjdk
#        name: set casc bundle and start Controller
#        shell: sh
#        run: |
#          java -jar ./jenkins-cli.jar -auth -auth ${{ vars.USER_NAME }}:${{ secrets.OC_TOKEN }} -s ${{ vars.oc-url }} casc-bundle-set-controller -b HA-HS -c workshop-controller 
#          java -jar ./jenkins-cli.jar -auth -auth ${{ vars.USER_NAME }}:${{ secrets.OC_TOKEN }} -s ${{ vars.oc-url }} managed-master-restart workshop-controller      

